### ISSUE TITLE
Tasks for v1.4 release cycle

### ISSUE THREAD

**Issue by sbueringer** [sbueringer/cluster-api#77]
Please see the corresponding section in [release-tasks.md](#TODO-after-merge) for task documentation.  

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.4 release cycle. Please modify according to the timeline 
  of the release cycle that should be tracked. 

Week 1:
* [ ] [Release Lead] Prepare main branch for development of the new release
* [ ] [Release Lead] Creating a new GitHub milestone

Week 1-4:
* [ ] [Release Lead] [Track] Remove previously deprecated code

Week 6:
* [ ] [Release Lead] Cut the v1.3.1 release

Week 9:
* [ ] [Release Lead] Cut the v1.3.2 release

Week 11-12:
* [ ] [Release Lead] [Track] Bump dependencies

Week 13:
* [ ] [Release Lead] Cut the v1.4.0-beta.0 release
* [ ] [Release Lead] Cut the v1.3.3 release

Week 14:
* [ ] [Release Lead] Cut the v1.4.0-beta.1 release

Week 15:
* [ ] [Release Lead] Create the release-1.4 release branch
* [ ] [Release Lead] Cut the v1.4.0-rc.0 release

Week 16:
* [ ] [Release Lead] Cut the v1.4.0-rc.1 release

Week 17:
* [ ] [Release Lead] Cut the v1.4.0 release
* [ ] [Release Lead] Cut the v1.3.4 release

When necessary:
* [ ] [Release Lead] [opt] [Track] Bump the ClusterAPI apiVersion
* [ ] [Release Lead] [opt] [Track] Bump the Kubernetes version
