### ISSUE TITLE
Tasks for v1.4 release cycle

### ISSUE THREAD

**Issue by sbueringer** [sbueringer/cluster-api#78]
Please see the corresponding section in [release-tasks.md](#TODO-after-merge) for task documentation.  

## Tasks

**Notes**:
* Weeks are only specified to give some orientation.
* The following is based on the v1.4 release cycle. Please modify according to the timeline 
  of the release cycle that should be tracked. 

Week -3 until 1:
* [ ] [Release Lead] Set a tentative release date for the minor release
* [ ] [Release Lead] Assemble release team

Week 1:
* [ ] [Release Lead] Finalize release team and schedule
* [ ] [Release Lead] Prepare main branch for development of the new release
* [ ] [Release Lead] Create a new GitHub milestone
* [ ] [Communications Manager] Add docs to collect release notes for users and migration notes for provider implementers
* [ ] [Communications Manager] Update supported versions

Week 1 until 4:
* [ ] [Release Lead] [Track] Remove previously deprecated code

Week 6:
* [ ] [Release Lead] Cut the v1.3.1 release

Week 9:
* [ ] [Release Lead] Cut the v1.3.2 release

Week 11 until 12:
* [ ] [Release Lead] [Track] Bump dependencies

Week 13:
* [ ] [Release Lead] Cut the v1.4.0-beta.0 release
* [ ] [Release Lead] Cut the v1.3.3 release

Week 14:
* [ ] [Release Lead] Cut the v1.4.0-beta.1 release
* [ ] [Release Lead] Select release lead for the next release cycle

Week 15:
* [ ] [Release Lead] Create the release-1.4 release branch
* [ ] [Release Lead] Cut the v1.4.0-rc.0 release
* [ ] [CI Manager] Setup jobs and dashboards for the release-1.4 release branch
* [ ] [Communications Manager] Ensure book for the new release is available

Week 15 until 17:
* [ ] [Communications Manager] Polish release notes

Week 16:
* [ ] [Release Lead] Cut the v1.4.0-rc.1 release

Week 17:
* [ ] [Release Lead] Cut the v1.4.0 release
* [ ] [Release Lead] Cut the v1.3.4 release
* [ ] [Release Lead] Organize release retrospective
* [ ] [Communications Manager] Change production branch in Netlify to the new release branch
* [ ] [Communications Manager] Update clusterctl links in the quickstart
* [ ] [CI Manager] Modify clusterctl tests on main to test the new v1.4.0 release

Continuously:
* [ ] [Communications Manager] Communicate key dates to the community
* [ ] [CI Manager] Monitor CI signal
* [ ] [CI Manager] Reduce the amount of flaky tests
* [ ] [CI Manager] Bug triage

If and when necessary:
* [ ] [Release Lead] [Track] Bump the ClusterAPI apiVersion
* [ ] [Release Lead] [Track] Bump the Kubernetes version
